services:
  db:
    container_name: postgres
  
    image: postgres:${POSTGRES_TAG}
    
    restart: always
    
    shm_size: 128mb
    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    ports:
      - 5432:5432
        
    networks:
      - localnet


  adminer:
    container_name: adminer

    image: adminer:${ADMINER_TAG}
    
    restart: always
    
    ports:
      - 8000:8080
    
    environment:
      - ADMINER_DESIGN=pappu687
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - localnet
    
    depends_on:
      - db

networks:
  localnet:
    name: localnet
